name: build-test-deploy
on: push
jobs: 
  build-using-node:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repository code
        uses: actions/checkout@v3
      - name: download, install and set up NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: 'latest'
      - run: npm version
      - run: npm install
      - run: npm run build
  test-using-node:
    needs: build-using-node
    runs-on: ubuntu-latest
    steps:
      - name: checkout repository code
        uses: actions/checkout@v3
      - name: download, install and set up NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: 'latest'
      - run: node -v
      - run: npm -v
      - run: npm install
      - run: npm test
        continue-on-error: true
  deploy-to-pages:
    needs: test-using-node
    permissions:
      contents: write
      pages: write
      id-token: write
    environment:
      name: Dev
      url:  ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: use node.js
        uses: actions/setup-node@v3
        with:
          node-version: 'latest'
      - name: configure github pages
        uses: actions/configure-pages@v3
        with:
          static_site_generator: next
      - run: npm install
      - run: npm run build
      - name: upload artifacts to pages
        uses: actions/upload-pages-artifact@v3
        with: 
          path: "./out"
      - name: deploy
        id: deployment
        uses: actions/deploy-pages@v4
